### PR TITLE
Toolbox to Julia 1.1

### PR DESCRIPTION
**Pull request by thjsal**

### CODE REVIEW

**Comment by thjsal** [comment]
Made toolbox work with Julia 1.1. 

1 thing to check: Was it ok to comment the line 86 of sys_io.jl (done in the last commit)? Otherwise it complains that T is not defined. This is a writedlm definition that is outside of any functions. Code seems to work without this.

**Comment by natj** [comment]
sys_io.jl does not have anything important as it is all WIP. So should be ok.

**Comment by natj** [comment]
let me know if you are done and I'l merge to master.

**Comment by thjsal** [comment]
Yes, It can be merged.

**Pull request merged**
